name: Sync Airtable Commissions

on:
  schedule:
    # Runs every 30 minutes
    - cron: '*/5 * * * *'
  workflow_dispatch: # Allows manual runs

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Call Supabase Function
        run: |
          curl -X POST \
            "https://sivtymavemdcwyxcshwk.supabase.co/functions/v1/sync-airtable-commissions" \
            -H "Authorization: Bearer ${{ secrets.SUPABASE_ANON_KEY }}" \
            -H "Content-Type: application/json"
